### ISSUE TITLE
bug(console): Remove placeholder text

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#1665]
Needs some actual text to replace the placeholder "Lorem ipsum" text that's there now.

![Image](https://user-images.githubusercontent.com/23303439/219086807-f7d0469c-3f52-404f-a3cd-2a3fc4fe3cad.png)

**Comment by picassobanana** [comment]
**Join our community**
Connect with us and stay up to date!

**Learn best practises**
Not sure where to start?




![Image](https://user-images.githubusercontent.com/103597761/219440507-5508d8f3-ba44-4bac-b47f-cc8a70301e06.png)


cc: @maurerbot
