### ISSUE TITLE
feat(profile): Applications listing and revocation modal

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#1669]
Following the Figma design in Applications > Applications view, implement:
- [ ] From Applications mockup: List application view
- [ ] From "Edit Access" mockup: modal (read-only - links/buttons aren't clickable other than Cancel)

**Comment by Cosmin-Parvulescu** [comment]
Could I get some links to the referenced Figma designs? @picassobanana 😁

**Comment by Cosmin-Parvulescu** [comment]
@betimshahini any tips on accessing scope data?

<img width="415" alt="image" src="https://user-images.githubusercontent.com/635806/220293231-70741807-5b1f-403f-940f-9592618c7f62.png">

**Comment by Cosmin-Parvulescu** [comment]
Following up on Scope structure; refresh tokens have a `scope` property which contains an array of encoded scopes:
- ex. scope://rollup.id/profile#read

We use this string to access human readable name:
```

**Comment by Cosmin-Parvulescu** [comment]
![Image](https://user-images.githubusercontent.com/635806/221531575-a940ad52-ead3-4771-a7ef-5edf428b41d8.png)
Is the UI still up to date? There is no authorization date or a property that represents the 'read-only' map.

Currently we can achieve something like:
![Image](https://user-images.githubusercontent.com/635806/221532246-2d7b947e-e73c-4fa7-9d68-f5f5b5727f3a.png)

**Comment by Cosmin-Parvulescu** [comment]
Given that we have no scopes atm, should we have an empty state for the modal?

**Comment by picassobanana** [comment]
The modal was designed to display scopes, approved date and allow revoking access per approval, if we don’t support any of that at the moment this might be a better solution for now:
<img width="1120" alt="Screenshot 2023-02-27 at 12 12 20" src="https://user-images.githubusercontent.com/103597761/221549102-0a39419f-f20a-425d-92a8-b1c44665d07b.png">
<img width="1094" alt="Screenshot 2023-02-27 at 12 16 39" src="https://user-images.githubusercontent.com/103597761/221549975-c5404124-5c67-46f5-a86c-371ffb5aa123.png">
