### ISSUE TITLE
feat(passport): Login screen with logged-in user

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#1759]
To enhance the user experience as well as work around issues as noted in #1692, the login screen should be enhanced to show the currently logged in user in addition to the options to log in with another account. This should be the new default behaviour, that replaces the auto-login behaviour that we have today. This is equivalent to `prompt=select_account`.

This new default behaviour should be overridable by the developer to do auto-login by using the `prompt=none` in the `/authorize` call

- [ ] Implement the V1 Figma design in https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=8567%3A21023&t=nNneSVPy9uyx4VUJ-0. *Note:* This ticket does NOT implement V2 design.
- [ ] Make `prompt=select_account` and `prompt=none` work as described above.

![Image](https://user-images.githubusercontent.com/23303439/220714561-b0adf956-3c4d-4dcb-8cb0-10cb0a0875a8.png)

**Comment by picassobanana** [comment]
V1 (Single Account) -[ Figma Link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=8567%3A21023&t=nNneSVPy9uyx4VUJ-0)


![Image](https://user-images.githubusercontent.com/103597761/221234193-5b2670ac-a40b-4c6a-bf7d-4b39fd2156ce.png)

V2 - (Multiple Accounts) [Figma Link](url)


![Image](https://user-images.githubusercontent.com/103597761/221234539-dfa2f7f5-2ee1-42ed-b6c1-6ab7ce8d552e.png)
