### ISSUE TITLE
chore(passport|profile|console): Mobile header and user info design across the apps

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#1965]
Currently, we have multiple design patterns when it comes to the two items below withing mobile views and there is an opportunity to make things more visually consistent, to match the consistency of other aspects of the designs across the apps.

- Header in mobile designs has the application name in console, but has it removed in profile. Ideally, we'd put the product names to fill the space between the logo and the hamburger menu on all apps' mobile views.
- The user info (name and avatar) are shown in some mobile nav menus (eg. profile) but not in others (eg. passport). Where they're shown, they look different. Would be good to have a similar design across all apps. This may include links to sign out (and possibly switch accounts, in the future for multi-account).

This tracks:
- [x] UX decisions and new figma
- [x] Implementation of changes above across the codebase

**Comment by picassobanana** [comment]
Links:
[Console Figma](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=9763-26477&t=GO14pfj9EHa3OBXu-0)
[Passport Figma](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=9763-27286&t=GO14pfj9EHa3OBXu-0)
[Profile Figma](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=9763-26261&t=GO14pfj9EHa3OBXu-0)


Changes:
- All headers will have full logo with application name (both mobile and desktop)
- Mobile menu in Console, Passport and Profile will share the same component displaying user info and logout icon.     

![Image](https://user-images.githubusercontent.com/103597761/228026755-6f8454e6-df0f-480c-ae96-042957f56606.png)


The component is ready for account switching if we support multi-account in the future. (TBD)

![Image](https://user-images.githubusercontent.com/103597761/228028960-7bddfe27-3f2d-4a78-a84f-cc1df08b661d.png)
