### ISSUE TITLE
chore(passport|profile|console): Different favicons for each app

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#1966]
As we have differently-coloured logos for each app, we need the same reflected on the favicons, so it's easier to visually distinguish the apps in the browser tab icons or in the browser's back button history. Same goes for app titles

Update app titles to:
- Passport - Rollup
- Console - Rollup
- Profile - Rollup

Use the favicons images below and set accordingly.

This tracks:
- [x] Decision
- [x] Asset work for new favicons
- [x] Implementation in the codebase

**Comment by picassobanana** [comment]
I like the idea 👍🏻 I think we should also unify the Title tags to 

> Rollup - Passport
> Rollup - Console
> Rollup - Profile


or 

> Passport - Rollup
> Console - Rollup
> Profile - Rollup

or 

> Passport
> Console
> Profile


**Preview:**
![Image](https://user-images.githubusercontent.com/103597761/227216829-9a1538e9-ec84-4559-887b-28fa39ede48c.png)

**Favicons:**



![Image](https://user-images.githubusercontent.com/103597761/227218314-91dedf4b-3ca0-4664-9a28-a24eba260f42.png)



![Image](https://user-images.githubusercontent.com/103597761/227218326-e43fd8e8-529f-4cc2-bb20-3a4106592384.png)



![Image](https://user-images.githubusercontent.com/103597761/227218341-4f90f9f3-d2eb-4514-9e23-a06c70ecc51c.png)
