### ISSUE TITLE
bug(passport): `error` param remains in params after successful authorization

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2063]
When going through an authorization flow, where a new email that's already connected elsewhere is added through the dropdown in the authz screen, we get the "Already connected" toast message, as expected.

This, however, puts an `error` param in the query params. This param is retained even after a successful authorization is done in the authorization screen. This results in a redirect URL as follows:
`http://(redirect_uri)/?error=ALREADY_CONNECTED&code=0xfa1ee9c7a1fbe90d1bf760437121cdbd31ee5dd26c659b3b&state=foo`

The error param should not be retained in the redirects facilitated by the authorization flow.

**Comment by Cosmin-Parvulescu** [comment]
Doesn't seem to be the case anymore. Parameter has changed from `error` to `

https://user-images.githubusercontent.com/635806/233049814-f9329d29-7da4-45b9-a395-4fe8ae2b2a99.mov
