### ISSUE TITLE
fix(console): OAuth copy to clipboard button does not work

### ISSUE THREAD

**Issue by szkl** [proofzero/rollupid#2092]
### Description

The copy buttons for the `client id` and the `client secret` fields do not work. The issue is persistent between reloads on current `main`.

### Steps to Reproduce

1. Open `console`
2. Create an app
3. Click to copy to clipboard buttons in OAuth section
4. Try to paste somewhere

### Expected Behavior

The content of the `client id` and `client secret` fields to be copied to the clipboard.

### Actual Behavior

The clipboard is not changed.

**Comment by poolsar42** [comment]
Closing since it's not related to our current state
