### ISSUE TITLE
feat(address): Add smart contract wallet generation support

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2114]
Dependent on #2112 

Based on experimentation in #ticket, add the following to address worker&DO.
- [ ] Pattern to import/inline a versioned smart contract code, statically. This smart contract code should be bundled as part of the address deployable bundle.
- [ ] Structure in Address DO to store the keypair that will be used by the smart contract
- [ ] `generateSmartContract()` that takes a versioned smart contract object and the public key of the keypair above, and generates a smart contract address which will be stored in the Address DO. 
- [ ] (TBD) Deploy the generated contract vs store to be lazy-deployed on first transaction.

**Comment by poolsar42** [comment]
Here's a quick [gist](https://gist.github.com/poolsar42/987829144b82ba1cf456dfb944bbc1a7) of how to deploy smart contract from worker
