### ISSUE TITLE
bug(passport): hover on sign out menu button actually logs out

### ISSUE THREAD

**Issue by szkl** [proofzero/rollupid#2183]
# Description

Steps to reproduce:
1. Sign in to Passport
2. Click to the profile picture button
3. Hover on the sign out button

The session cookie is cleared.

Note: The hover behavior should be checked everywhere.

**Comment by poolsar42** [comment]
Hi @szkl
It seems I can't reproduce it, can you please specify device? it might help

https://github.com/proofzero/rollupid/assets/33105890/7a9cc634-e724-4826-aa4e-06e2d478f923

**Comment by szkl** [comment]
I was not able to reproduce with a different browser.
