### ISSUE TITLE
fix(console): Invisible create app button

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [proofzero/rollupid#2324]
### Description

Create App button is not visible in the create app screen of the console application.

### Steps to Reproduce

1. Go to console app
2. Try to create new app
3. Enter name
4. Don't see button, but works if enter is clicked

### Expected Behavior

See button

### Actual Behavior

Button not seen

**Comment by poolsar42** [comment]
Didn't encounter this behaviour in any existing environment -- closing this ticket for this reason
