### ISSUE TITLE
chore(console): Add billing email selection dropdown

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2402]
Dependency on #2400 for `stripe` module.

To support use cases of sending billing/payment notifications to users, since the payments are separate from apps, we need a new billing/payment notification email selection to be available in the Billing and Invoicing page. 

- [x] UX
- [ ] Add email address as a required parameter to the purchase/remove methods in the `stripe` module. This email is to be included with the request under the `customer_email` field to Stripe's checkout session creation endpoint.
- [ ] Add email addressURN to Account DO's `servicePlans` key
- [x] Add an `EDGE_HAS_REF_TO` edge from AccountURN to email AddressURN
- [x] Add check in `getAddressReferenceTypes` for new billing notification email type.
- [x] Add check and copy for when trying to disconnect an email that's associated to billing notifications.

**Comment by picassobanana** [comment]
[Figma link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=12634-33215&t=ZOgjH65CVnlvEH3L-0)



Preview:
![Image](https://github.com/proofzero/rollupid/assets/103597761/b92f1c68-dec0-4ccc-a3eb-9a04c7d33988)
