### ISSUE TITLE
feat(console): Groups and group user management

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2452]
Implementation for: #2447 

- Groups are a top-level console feature, where users should be able to see and manage their groups
- Users can be added or removed (by any of their connected account identifiers) to it by anyone who is part of the group, with the creator of the group being automatically added upon creation. The last user in the group should not be able to remove themselves from it.

Tech consideration:
`IdentityGroup` should be a new node in the graph (hosted by account/core worker). Should be represented as an edge connecting one or many user identities to the group, by way of a `memberOf/group` tag

Figma: https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=12945-40286&mode=design&t=XVrNRlhnkzmh44F4-0
Frames:
- Groups
- Groups \ Group 1 (no button actions or data in applications list)
- Groups \ Add group member (all frames with this name, but no invite link generation)
- Groups \ Member invited

**Comment by Cosmin-Parvulescu** [comment]
@picassobanana for the listing of members in groups, is it intended that we list the `Account / Identity` for the invitee, or the `Address`?
