### ISSUE TITLE
chore(console): UI Cleanup

### ISSUE THREAD

**Issue by picassobanana** [proofzero/rollupid#2520]
[Figma Link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=13325-37029&mode=design&t=YdEppRvzt6FuE1cg-0)

- [x] 1 - Get rid of the white outline and heavy shadow on Hover
- [x] 2 - Get rid of the primary button white outline and if possible get rid of the “active/selected” state of the application  dropdown that causes the purple  outline around the dropdown
- [x] 3 - Change User Settings Icon to "TbUserCog”
- [x] 4 - Change the “base” card padding to: left&right:24px, top&bottom:16px and get rid of the shadow.
- [x] 5 - Change the radius on Billing&Invocing cards from .25rem to 0.5rem
- [x] 6 - Change the outline on dropdown field to gray-300 and change the radius of to 0.25rem
- [x] 7 - Sync the “ Ammount Per month” Styling in Billing&Invocing cards with the styling in purchase modal
- [ ] 8 - Make the close button inline with the modal heading
- [x] 9 - The submit button should be set to “disabled” state until user makes a change and both fields filled.
- [x] 10 - Please make sure this icon is set to: “TbWorld”
- [x] 11 - Align the "Users" heading with the card  in /dashboard
- [x] 12 - Change the "Connect email address to enable all features" from purple"Info" to orange "Warning"
- [x] 13 - Change the warning icon size from 16x16px to 32x32px
- [x] 14 - Change the radius values to: Large 16px, Medium 8px, Small -> none
- [x] 15 - Fix the image border overlay - the row should be extended or image cropped. 
- [x] 16 - When you upload an image the "remove" link should be indigo-500.
- [x] 17 - Email input field is not using the "ring" outline color from designer. 

Preview:
<img width="2182" alt="Screenshot 2023-07-19 at 12 25 56" src="https://github.com/proofzero/rollupid/assets/103597761/9feee43a-c310-4498-b680-2a3f51d928a6">
<img width="2352" alt="Screenshot 2023-07-20 at 10 42 05" src="https://github.com/proofzero/rollupid/assets/103597761/732be4d3-2191-4f59-b205-f89d201b102b">

**Comment by poolsar42** [comment]
#8 is heavy, I'll make a separate ticket for this one
