### ISSUE TITLE
chore(passport): handling invalid refresh token in Google OAuth

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2565]
An invalid refresh token breaks the Google address profile. The user should be notified that the account connection is broken and should be requested to grant offline access again by `prompt=consent` parameter. The access token (if expired the refresh token) would be used asynchronously. If the tokens do not work then loading the dashboard fails.

Any token can be revoked or invalidated by the user or the OAuth provider so this task could be considered for managing this broken state and prompting the user for re-authentication in all of the provider implementations.

**Comment by szkl** [comment]
> @szkl this has been addresses as part of the reconnect flow, right?

Yes. It is done.
