### ISSUE TITLE
chore(console): Onboarding flow for teams

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2645]
Follow on to #2562 and dependent on admin groups feature landing. 

Need to solution for first-time users choosing to create teams as well as think about the non-onboarding scenario of users who have onboarded in a personal context, creating a group and moving into a group context and if we need any CRM events for that.

**Comment by picassobanana** [comment]
### Group Creator Onboarding

[Figma Link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=15818-30701&mode=design&t=bP44cd2p67t7AUsV-0)

**Notes**
Skippable after step 2 is completed.

**Preview**
![Image](https://github.com/proofzero/rollupid/assets/103597761/d07edd5c-a206-454c-b38c-db76ed4b5f50)





### Group Invitee Onboarding

[Figma Link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=15818-31192&mode=design&t=bP44cd2p67t7AUsV-0)

**Notes**
Skippable after  step 1 is completed.

**Preview**
![Image](https://github.com/proofzero/rollupid/assets/103597761/25e035e0-a44c-4a3a-a286-fe6f962e6752)
