### ISSUE TITLE
fix(passport): "Continue with email" submission button below fold on mobile

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2704]
### Description

When choosing to "continue with email” on a mobile phone, the button “Send code” is not visible, as it’s below the fold, even though there’s a lot of space there. 

![Image](https://github.com/proofzero/rollupid/assets/23303439/0cba2f73-5c1b-4680-bec0-6a827d00872e)

**Comment by picassobanana** [comment]
Lets move the "Send Code" and "verify" buttons below the input field.

Preview:

![Image](https://github.com/proofzero/rollupid/assets/103597761/bbeb69e4-e799-455d-b816-b79756dcc7c3)

https://github.com/proofzero/rollupid/assets/103597761/f10a410d-2df6-46a2-9a0a-cffa84aca2d1
